### ISSUE TITLE
build error: Some ROM regions are overlapping

### ISSUE THREAD

**Issue by alissa-tung** [noteed/riscv-hello-c#2]
Hello, I am new to RISC-V and qemu and had build the example successfully. When exec
```sh
qemu-system-riscv64 -nographic -machine sifive_u -kernel build/bin/rv64imac/qemu-sifive_u/hello
```
it failed with the following messages

```
qemu-system-riscv64: Some ROM regions are overlapping
These ROM regions might have been loaded by direct user request or by default.
They could be BIOS/firmware images, a guest kernel, initrd or some other file loaded into guest memory.
Check whether you intended to load all this guest code, and whether it has been built to load to the correct addresses.

The following two regions overlap (in the memory address space):
  /usr/bin/../share/qemu/opensbi-riscv64-generic-fw_dynamic.bin (addresses 0x0000000080000000 - 0x0000000080012558)
  build/bin/rv64imac/qemu-sifive_u/hello ELF program header segment 0 (addresses 0x0000000080000000 - 0x0000000080000040)
```

The toolchain versions I had tested on are
- risc v gnu toolchain git
- qemu git
- risc v gnu toolchain archlinux repo binary
- qemu archlinux repo binary

**Comment by thusc** [comment]
Hi,

Your problem seems similar to https://github.com/noteed/riscv-hello-asm/issues/1 although you have slightly different (maybe improved?) error messages.

In particular, did you try to add `-bios none` ?

**Comment by alissa-tung** [comment]
> Hi,
> 
> Your problem seems similar to [noteed/riscv-hello-asm#1](https://github.com/noteed/riscv-hello-asm/issues/1) although you have slightly different (maybe improved?) error messages.
> 
> In particular, did you try to add `-bios none` ?

Thx for helping, I am going to inspect the linked issue.
I had tried, but ended up with no response on the screen.

Seems that change uart_base and bios none does not fix the issue.

**Comment by minhduc09777** [comment]
Thanks you ae
